import { units as u, decimal as d, mul, min, max, SCALE } from "./money.mjs";
export function itemMultiplier(items, config) {
  const bonuses = items
    .filter((i) => i.earningEnabled)
    .slice(0, 2)
    .map(
      (i) =>
        max(0n, u(i.earningMultiplier ?? "1") - SCALE) +
        u(i.bonusPercent ?? config.items.rarityBonus[i.rarity] ?? "0") / 100n,
    );
  const n =
    config.items.stacking === "multiplicative"
      ? bonuses.reduce((n, b) => mul(n, SCALE + b), SCALE)
      : SCALE + bonuses.reduce((n, b) => n + b, 0n);
  return min(n, u(config.items.maximumMultiplier));
}
export function activeEvents(config, mode, now) {
  return config.events.filter(
    (e) =>
      e.enabled &&
      Date.parse(e.startTime) <= now &&
      now < Date.parse(e.endTime) &&
      (!e.modes.length || e.modes.includes(mode)),
  );
}
export function temporalMultiplier(entries, mode, now) {
  const active = entries.filter(
    (e) =>
      e.enabled &&
      Date.parse(e.startTime) <= now &&
      now < Date.parse(e.endTime) &&
      (!e.modes.length || e.modes.includes(mode)),
  );
  const stack = active.filter((e) => e.stackable);
  let n = SCALE;
  const counts = new Map();
  for (const e of stack) {
    const source = e.source || e.id,
      count = counts.get(source) || 0;
    if (count >= e.maximumStack) continue;
    counts.set(source, count + 1);
    n = mul(n, u(e.multiplier));
  }
  return active
    .filter((e) => !e.stackable)
    .reduce((best, e) => max(best, u(e.multiplier)), min(n, 100n * SCALE));
}
// Central calculation for previews AND finalization. All amounts are decimal strings.
// Actions/participants are generated by the simulation; never accept this input from HTTP.
export function calculateEarnings(
  match,
  player,
  config,
  { dailyEarned = "0", final = false, now = Date.now() } = {},
) {
  const mode = config.modes[match.mode];
  const result = {
    eligibleScore: "0.0000",
    baseE: "0.0000",
    itemMultiplier: d(itemMultiplier(player.items || [], config)),
    modeMultiplier: mode?.multiplier || "0",
    survivalMultiplier: "1.0000",
    eventMultiplier: "1.0000",
    itemBonus: "0.0000",
    modeBonus: "0.0000",
    survivalBonus: "0.0000",
    eventBonus: "0.0000",
    bonusE: "0.0000",
    directRewards: "0.0000",
    bossRewards: "0.0000",
    winReward: "0.0000",
    eventRewards: "0.0000",
    capReduction: "0.0000",
    finalE: "0.0000",
    score: player.score || 0,
    reason: null,
    dailyCap: config.DAILY_E_CAP,
  };
  if (
    !config.enabled ||
    !mode?.earningEnabled ||
    (match.private && !config.privateEarning)
  )
    return { ...result, reason: "Earning disabled in this match" };
  if (!player.userId && !config.guestEarning)
    return { ...result, reason: "Sign in to earn E" };
  let eligible = 0n,
    base = 0n,
    itemBonus = 0n,
    modeBonus = 0n,
    waveBonus = 0n,
    eventBonus = 0n,
    direct = 0n,
    boss = 0n,
    win = 0n,
    event = 0n;
  const im = itemMultiplier(player.items || [], config);
  // Accumulate rational micro-units before rounding once per summary category.
  const DEN = 100n * SCALE ** 5n;
  let exactBase = 0n,
    exactItem = 0n,
    exactMode = 0n,
    exactWave = 0n,
    exactEvent = 0n;
  for (const a of player.actions || []) {
    const rule = config.actions[a.kind];
    if (!rule?.earnsE || !a.allowed) continue;
    const score = mul(BigInt(a.score) * SCALE, u(a.farmingMultiplier || "1"));
    eligible += score;
    let exact = score * u(config.E_PER_100_SCORE) * SCALE ** 4n;
    exactBase += exact;
    exact = (exact * im) / SCALE;
    exactItem += exact;
    exact = (exact * u(mode.multiplier)) / SCALE;
    exactMode += exact;
    const wm =
      match.mode === "survival" && rule.wave
        ? min(
            u(config.survival.maxMultiplier),
            u(config.survival.baseMultiplier) +
              BigInt(Math.floor(a.wave / config.survival.waveInterval)) *
                u(config.survival.waveIncrement),
          )
        : SCALE;
    result.survivalMultiplier = d(max(u(result.survivalMultiplier), wm));
    exact = (exact * wm) / SCALE;
    exactWave += exact;
    const em = temporalMultiplier(
      [...activeEvents(config, match.mode, a.at), ...(player.boosters || [])],
      match.mode,
      a.at,
    );
    result.eventMultiplier = d(max(u(result.eventMultiplier), em));
    exact = (exact * em) / SCALE;
    exactEvent += exact;
  }
  base = exactBase / DEN;
  itemBonus = exactItem / DEN - base;
  modeBonus = exactMode / DEN - exactItem / DEN;
  waveBonus = exactWave / DEN - exactMode / DEN;
  eventBonus = exactEvent / DEN - exactWave / DEN;
  for (const r of player.direct || []) {
    if (!r.allowed) continue;
    const amount = u(r.amount);
    direct += amount;
    if (r.type === "BOSS_REWARD") boss += amount;
    else if (r.type === "WIN_REWARD") win += amount;
    else event += amount;
  }
  const total = base + itemBonus + modeBonus + waveBonus + eventBonus + direct;
  let reward = total,
    dailyCap = config.DAILY_E_CAP,
    matchCap = mode.maxEPerMatch ?? config.MAX_E_PER_MATCH;
  for (const e of activeEvents(config, match.mode, match.closedAt || now)) {
    if (e.dailyCap != null) dailyCap = e.dailyCap;
    if (e.maxEPerMatch != null) matchCap = e.maxEPerMatch;
  }
  if (matchCap !== null) reward = min(reward, u(matchCap));
  const duration = Math.max(
    0,
    Math.min(match.closedAt || now, player.lastSeen || now) - player.joinedAt,
  );
  if (config.maximumEPerMinute !== null)
    reward = min(
      reward,
      (u(config.maximumEPerMinute) * BigInt(duration)) / 60000n,
    );
  if (dailyCap !== null)
    reward = min(reward, max(0n, u(dailyCap) - u(dailyEarned)));
  let reason = null;
  if (
    final &&
    (match.closedAt - match.startedAt < config.minimumMatchSeconds * 1000 ||
      player.activeMs < config.minimumActiveSeconds * 1000 ||
      player.score < config.minimumScore)
  ) {
    reward = 0n;
    reason = "Minimum participation not met";
  }
  if (dailyCap !== null && u(dailyEarned) >= u(dailyCap))
    reason = "Daily E Limit Reached";
  return {
    ...result,
    eligibleScore: d(eligible),
    baseE: d(base),
    itemBonus: d(itemBonus),
    modeBonus: d(modeBonus),
    survivalBonus: d(waveBonus),
    eventBonus: d(eventBonus),
    bonusE: d(itemBonus + modeBonus + waveBonus + eventBonus),
    directRewards: d(direct),
    bossRewards: d(boss),
    winReward: d(win),
    eventRewards: d(event),
    capReduction: d(total - reward),
    finalE: d(max(0n, reward)),
    dailyCap,
    reason,
  };
}
