import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { Readable } from 'node:stream';
import bs58 from 'bs58';
import { PGlite } from '@electric-sql/pglite';
import { WithdrawalStore, withdrawalQuote, createWithdrawalService } from './withdrawals.mjs';
const db=new PGlite();
await db.exec('CREATE TABLE users(id BIGINT PRIMARY KEY);INSERT INTO users VALUES(1);');
await db.exec(readFileSync(new URL('./migrations/001_e_economy.sql',import.meta.url),'utf8'));
await db.exec('UPDATE users SET e_balance=10000 WHERE id=1');
const pool={async query(sql,args){
  if(sql.includes('-- Additive:')){await db.exec(sql);return {rows:[],rowCount:0};}
  const r=await db.query(sql,args);return {...r,rowCount:sql.trim().startsWith('SELECT')?r.rows.length:r.affectedRows};
},async connect(){return {query:pool.query,release(){}};}};
const recipient=bs58.encode(randomBytes(32));
const outcomes=new Map();let submissions=0,timeout=false,fail=false;
const provider={lookup:async id=>outcomes.get(id),submit:async request=>{
  submissions++;
  const outcome={...request,id:request.idempotencyKey,status:fail?'failed':'completed',definitive:fail,finalized:!fail,signature:bs58.encode(randomBytes(64))};
  outcomes.set(request.idempotencyKey,outcome);
  if(timeout)throw Error('Network timeout after submission');
  return outcome;
}};
const limits={minimumK:'1000',perWithdrawalK:'5000',perUserDailyK:'10000',globalDailyK:'10000'};
const disabled=new WithdrawalStore(pool);await disabled.init();
await assert.rejects(disabled.reserve(1,recipient,'1000','request-000000000001'),/not enabled/);
const store=new WithdrawalStore(pool,{provider,limits});
assert.deepEqual(withdrawalQuote('1000'),{k:'1000.0000',usdcUnits:'1000000'});
assert.throws(()=>withdrawalQuote('0.0001'));
const first=await store.reserve(1,recipient,'1000','request-000000000001');
assert.equal((await store.reserve(1,recipient,'1000','request-000000000001')).id,first.id);
const balance=async()=>(await pool.query('SELECT e_balance FROM users WHERE id=1')).rows[0].e_balance;
assert.equal(await balance(),'9000.0000');
await assert.rejects(store.reserve(1,recipient,'2000','request-000000000001'),/reused/);
timeout=true;await store.processOne();
assert.equal(await balance(),'9000.0000','uncertain payout never refunds');
await pool.query("UPDATE k_withdrawals SET lease_until=NOW()-INTERVAL '1 minute'");
timeout=false;await store.processOne();
assert.equal(submissions,1,'recovery looks up submission instead of paying again');
assert.equal((await pool.query('SELECT state FROM k_withdrawals WHERE id=$1',[first.id])).rows[0].state,'completed');
assert.equal(await store.processOne(),false);
fail=true;const second=await store.reserve(1,recipient,'2000','request-000000000002');
assert.equal(await balance(),'7000.0000');await store.processOne();
assert.equal(await balance(),'9000.0000');
await store.applyOutcome(second,outcomes.get(second.id));assert.equal(await balance(),'9000.0000','refund is idempotent');
await assert.rejects(store.reserve(1,recipient,'6000','request-000000000003'),/limits/);
await pool.query("INSERT INTO e_flags(user_id,reason) VALUES(1,'test anomaly')");
await assert.rejects(store.reserve(1,recipient,'1000','request-000000000004'),/review/);
await pool.query('UPDATE e_flags SET reviewed_at=NOW()');
const third=await store.reserve(1,recipient,'1000','request-000000000005');
await store.applyOutcome(third,{...outcomes.get(first.id),destination:bs58.encode(randomBytes(32))});
assert.equal((await pool.query('SELECT state FROM k_withdrawals WHERE id=$1',[third.id])).rows[0].state,'review');
assert.equal(await balance(),'8000.0000');
assert.equal((await pool.query("SELECT * FROM e_transactions WHERE type='WITHDRAWAL_RELEASE'")).rows.length,1);
const service=createWithdrawalService({pool,session:async()=>({id:1})});
await service.ready;
const req=Readable.from(['{}']);req.method='POST';req.headers={host:'game.test',origin:'https://game.test'};
let httpStatus;
await service(req,{writeHead(s){httpStatus=s;},end(){}},'/api/withdrawals');
assert.equal(httpStatus,503);
assert.equal(await balance(),'8000.0000','disabled public API never debits K');
await service.close();
await db.close();
console.log('PASS withdrawals: disabled default, exact rate, reservation, retries, timeout recovery, single payout/refund, limits, account review, mismatched provider response');
