// Weapon stats for the arsenal. Times are in seconds.
// `key` is the keyboard binding shown in the HUD (digits for the first ten guns,
// letters for the rest, "V" for the blade). `sound` maps to a profile in
// AudioManager.playShot(). The scroll wheel cycles through everything.
export const WEAPONS = [
  {
    id: 'sidearm',
    name: 'Sheriff',
    key: '1',
    kind: 'hitscan',
    sound: 'sidearm',
    damage: 51,             // 2-shot body kill (100 HP / 51 ≈ 2 shots)
    headshotMultiplier: 2.0, // 1-shot headshot kill
    pellets: 1,
    spread: 0.004,
    fireRate: 0.55,
    automatic: false,
    magSize: 6,
    reserveMax: 36,
    reloadTime: 1.4,
    range: 140,
    recoil: 0.035,
    color: 0x2b2f36
  },
  {
    id: 'uzi',
    name: 'Uzi',
    key: '2',
    kind: 'hitscan',
    sound: 'smg',
    damage: 12,
    pellets: 1,
    spread: 0.02,
    fireRate: 0.07,
    automatic: true,
    magSize: 32,
    reserveMax: 160,
    reloadTime: 1.5,
    range: 80,
    recoil: 0.013,
    color: 0x202227
  },
  {
    id: 'levershotgun',
    name: 'Lever Shotgun',
    key: '3',
    kind: 'hitscan',
    sound: 'shotgun',
    damage: 10,
    pellets: 8,
    spread: 0.085,
    fireRate: 0.7,
    automatic: false,
    magSize: 6,
    reserveMax: 30,
    reloadTime: 2.0,
    range: 30,
    recoil: 0.05,
    color: 0x6b4a2f
  },
  {
    id: 'm4',
    name: 'M4 Carbine',
    key: '4',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 22,
    pellets: 1,
    spread: 0.009,
    fireRate: 0.1,
    automatic: true,
    magSize: 30,
    reserveMax: 120,
    reloadTime: 1.8,
    range: 150,
    recoil: 0.02,
    color: 0x2a2d33
  },
  {
    id: 'm16',
    name: 'M16A2',
    key: '5',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 24,
    pellets: 1,
    spread: 0.009,
    fireRate: 0.1,
    automatic: true,
    magSize: 20,
    reserveMax: 120,
    reloadTime: 2.0,
    range: 160,
    recoil: 0.02,
    color: 0x1a1c20
  },
  {
    id: 'rifle',
    name: 'Falcon Rifle',
    key: '6',
    kind: 'hitscan',
    sound: 'rifle',
    damage: 24,
    pellets: 1,
    spread: 0.01,
    fireRate: 0.13,
    automatic: true,
    magSize: 28,
    reserveMax: 112,
    reloadTime: 1.9,
    range: 140,
    recoil: 0.022,
    color: 0x3f4a3a
  },
  {
    id: 'lmg',
    name: 'M240 Bravo',
    key: 'H',
    kind: 'hitscan',
    sound: 'lmg',
    damage: 20,
    pellets: 1,
    spread: 0.022,
    fireRate: 0.09,
    automatic: true,
    magSize: 100,
    reserveMax: 200,
    reloadTime: 4.5,
    range: 160,
    recoil: 0.03,
    color: 0x23262b
  },
  {
    id: 'rpg',
    name: 'RPG-7',
    key: 'G',
    kind: 'rocket',
    sound: 'rpg',
    damage: 130,
    splashRadius: 5.5,
    splashMin: 0.25,
    rocketSpeed: 40,
    pellets: 1,
    spread: 0,
    fireRate: 1.2,
    automatic: false,
    magSize: 1,
    reserveMax: 6,
    reloadTime: 3.2,
    range: 220,
    recoil: 0.09,
    color: 0x33363b
  },
  {
    id: 'boltsniper',
    name: 'Precision Bolt',
    key: 'B',
    kind: 'hitscan',
    sound: 'sniper',
    damage: 110,
    pellets: 1,
    spread: 0.0008,
    fireRate: 1.4,
    automatic: false,
    magSize: 5,
    reserveMax: 25,
    reloadTime: 2.8,
    range: 320,
    recoil: 0.06,
    scoped: true,
    color: 0x1f2228
  },
  {
    id: 'knife',
    name: 'Combat Knife',
    key: 'C',
    kind: 'melee',
    damage: 55,            // melee stab damage
    fireRate: 0.32,
    range: 2.2,
    arc: 0.9,
    throwable: true,
    throwSpeed: 42,
    throwDamage: 9999,     // one-hit kill on throw
    throwCooldown: 0.85,   // seconds before you pull a fresh knife
    throwRewardMult: 3,    // 3x coins/score/xp — only on a thrown kill
    color: 0x9aa0a8
  },
  {
    id: 'sword',
    name: 'Reaver Blade',
    key: 'V',
    kind: 'melee',
    damage: 65,
    fireRate: 0.45,
    range: 2.6,
    arc: 1.0,
    color: 0xc7ccd1
  }
];

export function getWeapon(id) {
  return WEAPONS.find((w) => w.id === id);
}
