export const GAME_MODES = [
  {
    id:        'deathmatch',
    name:      'FREE FOR ALL',
    icon:      '⚔',
    tag:       'FFA',
    desc:      'Every Spartan for themselves. 8 players, 8 minutes. Kill streaks multiply coin rewards.',
    color:     '#ff5c5c',
    botCount:  7,
    noRespawn: false,
    timeLimit: 480,
    lives:     Infinity,
    waves:     false,
    isZombie:  false,
  },
  {
    id:        'teamslayer',
    name:      'TEAM SLAYER',
    icon:      '🛡',
    tag:       '4v4',
    desc:      'Alpha vs Bravo. First team to 50 kills wins. Coordinate with your fireteam.',
    color:     '#ff8c00',
    botCount:  7,
    noRespawn: false,
    timeLimit: 600,
    lives:     Infinity,
    waves:     false,
    isZombie:  false,
  },
  {
    id:        'ctf',
    name:      'CAPTURE THE FLAG',
    icon:      '🚩',
    tag:       '4v4',
    desc:      'Steal the enemy flag and return it to your base. First to 3 captures wins.',
    color:     '#00aaff',
    botCount:  7,
    noRespawn: false,
    timeLimit: 900,
    lives:     Infinity,
    waves:     false,
    isZombie:  false,
    comingSoon: true,
  },
  {
    id:        'koth',
    name:      'KING OF THE HILL',
    icon:      '⭐',
    tag:       'FFA',
    desc:      'Capture and hold the hill. Accumulate 60 seconds of control time to win.',
    color:     '#ccaa00',
    botCount:  7,
    noRespawn: false,
    timeLimit: 600,
    lives:     Infinity,
    waves:     false,
    isZombie:  false,
    comingSoon: true,
  },
  {
    id:        'survival',
    name:      'FIREFIGHT',
    icon:      '🧟',
    tag:       'CO-OP',
    desc:      'PvE co-op defense. Up to 5 Spartans. Survive escalating waves — revive fallen teammates.',
    color:     '#44cc22',
    botCount:  0,
    noRespawn: true,
    timeLimit: 0,
    lives:     Infinity,
    waves:     false,
    isZombie:  true,
  },
];

export function getMode(id) {
  return GAME_MODES.find(m => m.id === id) || GAME_MODES[0];
}
